name: Deploy server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Deploy in Bizfly App Engine
        run: curl -X POST ${{ secrets.AUTO_DEPLOY_SERVER }}
